
enum TokenType {
    start_of_line,
    semicolon_comment,
    asterisk_comment,
    directive,
    string,
    string_escape,
    macro_escape,
    macro_argument,
    string_interpolation,
    space,
    operator,
    keyword,
    region,
    function,
    opcode,
    register,
    condition,
    macro_call,
    identifier,
    fixed_point_number,
    decimal_number,
    hex_number,
    binary_number,
    octal_number,
    gbgfx_number,
    comma,
    colon,
    open_bracket,
    close_bracket,
    open_paren,
    close_paren,
    unknown,
    replaced,
    end_of_line
}

export default TokenType
